name: echo sample
on: ['push']

jobs:
  echo:
    runs-on: ubuntu-18.04
    steps:
    - run: TEMP=`echo test temp`
      shell: bash
    - uses: docker://ubuntu:18.04
      with:
        entrypoint: /bin/echo
        args: $TEMP
